security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    MZhuravlev: { password: 1234qwer, roles: [ 'ROLE_USER' ] }
                    SKatorgin: { password: 1234qwer, roles: [ 'ROLE_USER' ] }
                    PKurkutov: { password: 1234qwer, roles: [ 'ROLE_USER' ] }
                    SKrivitsky: { password: 1234qwer, roles: [ 'ROLE_USER' ] }

    firewalls:
        wclock:
            remember_me:
                key:      "%secret%"
                lifetime: 3153600 # 365 days in seconds
                path:     /wclock
                domain:   ~ # Defaults to the current domain from $_SERVER
            pattern:  ^/wclock
            security: true
            form_login:
                check_path: w_clock_login_check
                login_path: w_clock_login
            logout:
                path: w_clock_logout
                target: w_clock_homepage


        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: "^/wclock", role: ROLE_USER, ip: %access_ip% }
        - { path: "^/wclock", role: ROLE_ADMIN }