w_clock_login:
    path:     /login
    defaults: { _controller: WClockBundle:Security:index}

w_clock_login_check:
    path:     /wclock/check
    defaults: { _controller: WClockBundle:Security:check}

w_clock_logout:
    path:     /wclock/logout
    defaults: { _controller: WClockBundle:Security:logout}

w_clock_state:
    path:     /wclock/state
    defaults: { _controller: WClockBundle:Ajax:state, _format: json }
    methods: [POST, GET]

w_clock_info:
    path:     /wclock/info
    defaults: { _controller: WClockBundle:Ajax:info }
    methods: [POST, GET]

w_clock_action:
    path:     /wclock/action
    defaults: { _controller: WClockBundle:Ajax:index, _format: json }
    methods: [POST, GET]

w_clock_report:
    path:     /wclock/report/{slug}
    defaults: { _controller: WClockBundle:Report:index, slug: ""}



w_clock_homepage:
    path:     /wclock/
    defaults: { _controller: WClockBundle:Default:index }

