w_clock_login:
    path:     /login
    defaults: { _controller: WClockBundle:Security:index}

w_clock_login_check:
    path:     /wclock/check
    defaults: { _controller: WClockBundle:Security:check}

w_clock_logout:
    path:     /wclock/logout
    defaults: { _controller: WClockBundle:Security:logout}

w_clock_action:
    path:     /wclock/action
    defaults: { _controller: WClockBundle:Ajax:index, _format: json }
    methods: [POST]

w_clock_report:
    path:     /wclock/report
    defaults: { _controller: WClockBundle:Report:index }

w_clock_homepage:
    path:     /wclock/
    defaults: { _controller: WClockBundle:Default:index }

