parameters:
#    w_clock.example.class: LeaderIT\Bundle\WClockBundle\Example
     w_clock.class: LeaderIT\Bundle\WClockBundle\WClock

services:
#    w_clock.example:
#        class: %w_clock.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     w_clock:
         class: %w_clock.class%
         arguments: []
